import {
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Stack,
  TextField,
  Typography,
} from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { AddUserButtonDialog } from '../src/components/AddUserButtonDialog';
import CalculateCleaningUser from '../src/components/CalculateCleaningUser';
import UsersList from '../src/components/UsersList';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1">Welcome</Typography>
        <Stack direction="row">
          <AddUserButtonDialog />
          <Box sx={{ ml: 2 }} />
          <CalculateCleaningUser />
        </Stack>
        <Box sx={{ mt: 2 }} />
        <UsersList />
      </main>
    </div>
  );
};

export default Home;
