import { Add } from '@mui/icons-material';
import { Box, Fab, Stack, Tab, Tabs, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import AbsencesList from '../src/components/AbsencesList';
import CalculateCleaningUser from '../src/components/CalculateCleaningUser';
import CleaningsList from '../src/components/CleaningsList';
import { DialogsHolder } from '../src/components/DialogsHolder';
import RoomsList from '../src/components/RoomsList';
import SettingsTab from '../src/components/SettingsTab';
import { TabPanel } from '../src/components/TabPanel';
import UsersList from '../src/components/UsersList';
import { useTabStore } from '../src/stores/tabStore';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { activeTab, setActiveTab } = useTabStore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography sx={{ mb: 2 }} variant="h2">
          Welcome
        </Typography>
        <CalculateCleaningUser />
        <Box sx={{ my: 2 }} />

        <Tabs
          value={activeTab}
          onChange={(_, v) => setActiveTab(v)}
          sx={{ mb: 2 }}
        >
          <Tab label="Users" />
          <Tab label="Cleanings" />
          <Tab label="Rooms" />
          <Tab label="Absence" />
          <Tab label="Settings" />
        </Tabs>

        <TabPanel index={0}>
          <UsersList />
        </TabPanel>
        <TabPanel index={1}>
          <CleaningsList />
        </TabPanel>
        <TabPanel index={2}>
          <RoomsList />
        </TabPanel>
        <TabPanel index={3}>
          <AbsencesList />
        </TabPanel>
        <TabPanel index={4}>
          <SettingsTab />
        </TabPanel>
      </main>
      <DialogsHolder />
    </div>
  );
};

export default Home;
